OPCION_HORIZONTAL_IZQUIERDA = "Izquierda"
OPCION_HORIZONTAL_DERECHA = "Derecha"
OPCION_HORIZONTAL_CENTRO = "Centro"

OPCION_VERTICAL_ARRIBA = "Arriba"
OPCION_VERTICAL_ABAJO = "Abajo"
OPCION_VERTICAL_CENTRO = "Centro"

NOMBRE_CARPETA_SALIDA = "waterpy"